### ISSUE TITLE
Developer documentation links in readme not working

### ISSUE THREAD

**Issue by JHuiz** [Accenture/sfmc-devtools#1]
First of all, thanks for this great work, it will be some time before I get to hopefully use it, but this is really a great step forward in SFMC development.

I was just curious to read more in the developer documentation you mention at the end of the [readme](https://github.com/Accenture/sfmc-devtools#94-developer-documentation), but the documents the links seem to be referring to are missing (there is also no docs folder in the repo). Are these docs not ready yet or are they accidentally missing and can they be added?

**Comment by JoernBerkefeld** [comment]
oh, thank you - probably forgot to stage those. let me look into it :)

**Comment by JoernBerkefeld** [comment]
had a bad gitignore entry preventing us from pushing the developer docs... fixed now

**Comment by JHuiz** [comment]
Thanks for the quick follow-up!
