### ISSUE TITLE
[BUG] when trying to retrieve BU 

### ISSUE THREAD

**Issue by SarikaBhosale11** [Accenture/sfmc-devtools#101]
**Describe the bug**
trying to retrieve BU, only this particular BU in SFMC instance failed to retrieve showing following error info. While when tried to retrieve other BU from same SFMC instance, It retrieved well.

**Comment by SarikaBhosale11** [comment]
remaining part of screenshot
![image](https://user-images.githubusercontent.com/77027445/128830562-7a6adf17-6ef9-4405-9c93-a8d46124f515.png)

**Comment by JoernBerkefeld** [comment]
as discussed, the issue was based on putting your project folder (git repo) inside of your one drive folder which then caused bad interaction
