### ISSUE TITLE
[BUG] unable to deploy content builder child folder if parent folder already exists

### ISSUE THREAD

**Issue by david-robuck** [Accenture/sfmc-devtools#1122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- In the content builder UI, there is an existing folder called "Journeys" located at the path "Content Builder/Journeys". 
- In my local VS Code, I have a code snippet with the key "CLP-GEN-CDS-1_dev" at the path "marketing-cloud/deploy/myCompany/_ParentBU_/asset/other". There are no other files in the deploy directory. 
- The JSON file for this asset defines the folder path as which has a "r__folder_Path": "Content Builder/Journeys/Generic"`

- When running the command `mcdev deploy myCompany/_ParentBU_ asset`, two folder files are created in deploy: Content Builder/Journeys & Content Builder/Journeys/Generic.
- When the asset itself attempts to deploy, the displayed message says "Dependent folder with Path='Content Builder/Journeys/Generic' was not found on your BU"

I have attached the log file from the attempted deployment as well as the two json files representing the auto-generated folders (I have changed the file extensions from .json to .txt so I could upload them here).
 
[mcdevResults.log](https://github.com/Accenture/sfmc-devtools/files/12812377/mcdevResults.log)
[Journeys.folder-meta.txt](https://github.com/A
[Generic.folder-meta.txt](https://github.com/Accenture/sfmc-devtools/files/12812439/Generic.folder-meta.txt)
ccenture/sfmc-devtools/files/12812434/Journeys.folder-meta.txt)

### Expected Behavior

The new subfolder "Generic" would be created and the asset "CLP-GEN-CDS-1_dev" would be created in this folder. 

### Steps To Reproduce

1. Create a folder in content builder
2. Place an asset in your local deploy folder which is defined to be saved in a subfolder of the existing folder you created in step 1. 
3. run mcdev deploy for the asset metadata
4. Review deploy folder where the desired new folder will have been created under deploy/folder
5. Review mcdev logs to see the error message that the asset could not be created as a dependent folder is missing.

### Version

5.3.0

### Environment

- OS: macOS 14.0
- Node: 20.5
- npm: 10.0

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

This appears to be a bug as mcdev is actively generating the required folder files needed to create the path the asset should be saved in. 

If I delete the "Journeys" folder in the UI and then re-run the same command, both folders and the asset are deployed successfully.  

**Practical context**
We are trying to retrieve metadata from one BU and deploy it into another. So in this example we are trying to extend the existing folder structure and add a new asset in the target BU.

**Comment by JoernBerkefeld** [comment]
hi @david-robuck happy to help you. first, let's double-check which version of mcdev you are running. 
your log file included color codes which were finally removed from being added to log files in mcdev 5.2.0 --> im assuming you might be running on an older version?

Also, your log file does not start with a line that looks like `15:46:07.661 debug: :: mcdev 5.3.0` - thats my 2nd indicator ;-)


Could you please run `mcdev --version` to confirm the actual version for me?

**Comment by JoernBerkefeld** [comment]
sorry, forgot to give you step 2: 
please re-run your deploy command but append `--api=log` to it. Then, share the newly generated log file. That will add additional information to the log that is otherwise omitted.

Example: `mcdev deploy myCompany/_ParentBU_ asset --api=log`

**Comment by david-robuck** [comment]
Thanks for the reply @JoernBerkefeld , here is another log file as requested with the additional `--api-log` param. It is for a different subfolder but the scenario and result is the same. Also the mcdev version is definitely 5.3.0 when running the `mcdev --version` command - not sure the appearance of the log is not in line with expectations for that version. 
[mcdevResults2.txt](https://github.com/Accenture/sfmc-devtools/files/12850951/mcdevResults2.txt)

**Comment by JoernBerkefeld** [comment]
strange - im actually quite certain that whatever creates your log files is another version than what you run when you type mcdev --version. I dont know how thats happening right now, though im guessing local vs global install, but that is difficult to debug just with text... would it be ok if we hopped on a video call to figure this out?

if yes, lets connect on LinkedIn to find a slot and share call details: https://www.linkedin.com/in/joernberkefeld/ -- im also open for alternatives if you prefer that. I do want to get to the bottom of this :)

**Comment by david-robuck** [comment]
@JoernBerkefeld today I was prompted to do an `mcdev upgrade` and after this I have been able to successfully deploy a content builder subfolder that had spaces in it. So I will mark this one as resolved for now. Thanks.
