### ISSUE TITLE
[BUG] incorrect warning: "Could not find mobileKeyword"

### ISSUE THREAD

**Issue by david-robuck** [Accenture/sfmc-devtools#1132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When retrieving transactionalSMS, I get a warning for each one that the mobileKeyword could not be found. Even though that keyword exists and has been retrieved. 
<img width="1037" alt="transactionalSMS warning" src="https://github.com/Accenture/sfmc-devtools/assets/69225649/35fe351c-106b-4e16-a4d1-0e5f54fb1bac">

### Expected Behavior

The warning should not be shown, rather an info should confirm the successful retrieve of the transactionalSMS

### Steps To Reproduce

3. Run '...'
4. See error...

### Version

6.0.0

### Environment

- OS: macOS 14.0
- Node: 20.5.0
- npm: 10.0

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by JoernBerkefeld** [comment]
hi @david-robuck - somehow i didnt notice this issue. given that this part of the solution received major attention though, can I assume it's no longer a problem?

**Comment by david-robuck** [comment]
All good @JoernBerkefeld confirming this behaviour appears to be resolved. I did a full retrieve on `transactionalSMS` with no issues on the current version. Thanks~

**Comment by JoernBerkefeld** [comment]
thank you! :)
