### ISSUE TITLE
[BUG] error when deploying dataExtension "SQL statement nested too deeply"

### ISSUE THREAD

**Issue by david-robuck** [Accenture/sfmc-devtools#1133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In my deploy folder I have 984 dataExtensions. When running the deploy command, it fails and I'm shown the message "Some part of your SQL statement is nested too deeply. Rewrite the query or break it up into smaller queries." I believe this is a MS SQL Server error message and not related to query activities I have created in Marketing Cloud. 

I have tried to isolate a specific dataExtension that could be causing the issue, but it seems the error is occurring based on the number of dataExtensions I am trying to deploy at once. 

Please see the attached log which shows the error on line 38. This occurs while caching dataExtensionField. 

[mcdevResults.txt](https://github.com/Accenture/sfmc-devtools/files/12923853/mcdevResults.txt)

### Expected Behavior

dataExtension can be successfully deployed. 

### Version

6.0.0

### Environment

- OS: 16.0
- Node: 20.5.0
- npm: 10.0

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by david-robuck** [comment]
@JoernBerkefeld confirming this is a real issue I am still experiencing. Are you familiar with this behaviour?

**Comment by JoernBerkefeld** [comment]
Hi @david-robuck that error message is generated by the server. Means it rejects your deployment. I'm assuming you deploy queries as well? 

Could you try this again now, since you have 6.0.0 installed, and again try to include the parameter `--api=log` please to enhance the log? I'm hoping that your logs finally look different.

Also, question: are you changing the filename or is it created by some script? I'm asking for the latest file in your /logs/ folder that ends on .log (not on error.log)

**Comment by david-robuck** [comment]
Here is that file @JoernBerkefeld thanks for your help!

[2023-10-25T00.48.43.958Z.log](https://github.com/Accenture/sfmc-devtools/files/13149253/2023-10-25T00.48.43.958Z.log)

**Comment by JoernBerkefeld** [comment]
Perfect. May I assume you sent me the cli output, copied or routed into a file before? 
If yes, I suppose I need to improve on how I ask for logs. Sorry about that. 

My kid is sick at home, might take a bit for me to look through the log.

**Comment by JoernBerkefeld** [comment]
Had a first chance: looks like mcdev is trying to download too many fields by dataExtension key during the initial caching. That needs to be batched to fix it. I'll get on it soon

**Comment by david-robuck** [comment]
Yes that's right. I'm sorry I didn't even know about that logs folder before.

**Comment by david-robuck** [comment]
@JoernBerkefeld just checking as this one as it is showing two tasks done. Will this bug fix be included in an upcoming release?

**Comment by JoernBerkefeld** [comment]
sorry, couldnt spend any time on this any earlier :(
I did look at it again just now and ran a test to deploy 1000 DEs:
![image](https://github.com/Accenture/sfmc-devtools/assets/1917227/f88f7487-5672-49bf-b893-6e8c5807d084)

after tweaking the code i re-ran the test with this result:
![image](https://github.com/Accenture/sfmc-devtools/assets/1917227/4944d1d3-b853-4680-9d63-1b0595e7a0d0)

looks like this is solved, @david-robuck :) will release the fix soon

**Comment by david-robuck** [comment]
Thank you @JoernBerkefeld - this is great news!
