### ISSUE TITLE
[BUG] MID is automatically appended customerKey of deployed assets

### ISSUE THREAD

**Issue by david-robuck** [Accenture/sfmc-devtools#1156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running the `mcdev deploy` command for an asset targeting a child BU called prod, the asset is created with the customerKey as expected based on the json file. However when running the same command targeting _ParentBU_ (called dev) or another child BU (called uat), the MID is getting automatically appended at the end of the customerKey. 

<img width="807" alt="164cbb13-d72e-4508-8fb4-254f4d9c12ec" src="https://github.com/Accenture/sfmc-devtools/assets/69225649/4259a44b-fa0b-4342-92da-a1d5629ab0e2">

### Expected Behavior

The customerKey of the newly created asset should match the .amp and .json filenames as well as the customerKey defined in the .json file. 

### Version

6.0.0

### Environment

- OS: macOS 14.2.1
- Node: 20.5.0
- npm: 10.0

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by stijnhoste** [comment]
I think this is by design, because the external key of assets has to be unique across the whole MC instance (because of Shared Content).

**Comment by david-robuck** [comment]
Yes I’m aware of that. In my testing I chose key that definitely did not already exist across thes enterprise. On Dec 28, 2023, at 9:15 PM, stijnhoste ***@***.***> wrote:﻿
I think this is by design, because the external key of assets has to be unique across the whole MC instance (because of Shared Content).

**Comment by david-robuck** [comment]
Here is the latest log when deploying the single file "dupe-test3"
<img width="916" alt="dupe-test3" src="https://github.com/Accenture/sfmc-devtools/assets/69225649/05bf4656-7c28-4b79-a9f8-8e8cab8b7845">

**Comment by david-robuck** [comment]
Ok I found the issue. The json file I was deploying still had the `memberId` value representing the other business unit (not the one I was deploying to). After fixing this value the result was as expected.

**Comment by JoernBerkefeld** [comment]
thank you for supporting this @stijnhoste and thank you for reporting it & documenting your way around it here @david-robuck  

❤️
