### ISSUE TITLE
[FEATURE] ensure eslint + prettier are installed with the same version in the project as in mcdev

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools#125]
if we continue to simply run `npm install eslint prettier` then the results from mcdev's auto formatting and what happens when you hit SAVE in your IDE might differ

**Comment by DougMidgley** [comment]
Need to determine if we want to just enforce this as a pre-requisite of using mcdev. the more options we have the more coding is required. I would say, we simply take the mcdev version and ask users to update accordingly. potential similar discussion with npm-check - if we enforce mcdev version, we likely dont need npm-check

**Comment by JoernBerkefeld** [comment]
not sure what this has to do with npm-check - which we only use for similar purposes as what dependabot is doing now

**Comment by JoernBerkefeld** [comment]
https://docs.npmjs.com/cli/v8/using-npm/config#save-prefix
_For example if a package has version 1.2.3, by default its version is set to ^1.2.3 which allows minor upgrades for that package, but after npm config set save-prefix='~' it would be set to ~1.2.3 which only allows patch upgrades._

--> lets go with prefix ~

requires a new config file named .npmrc in the project root with only content `save-prefix='~'`
we have something similar in our mcdev root but with no prefix which does not update on `npm install` execution to better control the version

**Comment by JoernBerkefeld** [comment]
Calling `npm update` will do what's mentioned above: update dependencies while respecting semantic versioning. To add or upgrade a dependency in a package

means we could run `npm install`, followed by `npm update` to get latest patch releases in?
your thoughts?

**Comment by JoernBerkefeld** [comment]
no longer asking if one wants to update but rather figure the need out ourselves:
![image](https://user-images.githubusercontent.com/1917227/177512713-f80989af-89cd-4b43-9b5f-4a8788b946e0.png)
