### ISSUE TITLE
deploy importFile failing with "Cannot read properties of undefined (reading 'c__destinationType') (undefined)"

### ISSUE THREAD

**Issue by david-robuck** [Accenture/sfmc-devtools#1376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have been able to deploy all files successfully prior to upgrading to 7.0.0. Now when deploying an importFile with no change s to its metadata I get the following error message: "Cannot read properties of undefined (reading 'c__destinationType') (undefined)"
<img width="1203" alt="error_log" src="https://github.com/Accenture/sfmc-devtools/assets/69225649/c5c3b693-be5c-4ef8-b3bf-4af7c97be585">

Here is the contents of my file. 

```json
{
    "allowErrors": true,
    "customerKey": "SYS-LOL-camp-enrolment-staging-au",
    "createdDate": "2024-05-20T18:46:09.963",
    "modifiedDate": "2024-05-20T22:04:13.817",
    "dateFormatLocale": "en-US",
    "deleteFile": false,
    "fieldMappings": [],
    "fieldMappingType": "InferFromColumnHeadings",
    "fileNamingPattern": "camp_enrolment.csv",
    "fileType": "CSV",
    "filter": "",
    "hasColumnHeader": true,
    "isOrderedImport": true,
    "isSequential": true,
    "maxFileAgeHours": 0,
    "maxImportFrequencyHours": 0,
    "maxFileAgeScheduleOffsetHours": 0,
    "name": "Lola - Camp Enrolment Staging AU",
    "notificationEmailAddress": "",
    "sendEmailNotification": false,
    "standardQuotedStrings": true,
    "fileTransferLocationTypeId": 0,
    "r__fileLocation_name": "SFTP - Import",
    "c__destinationType": "DataExtension",
    "r__dataExtension_CustomerKey": "SYS-LOL-camp-enrolment-staging-au",
    "c__subscriberImportType": "DataExtension",
    "c__dataAction": "Overwrite"
}
```

### Expected Behavior

importFile should still be able to deploy. 

### Version

7.0.0

### Environment

- OS: macOS 14.5
- Node: 22.3
- npm: 10.8.1

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by david-robuck** [comment]
@JoernBerkefeld would love some help on this please when you can. Thanks.

**Comment by JoernBerkefeld** [comment]
Hi there, always happy. Will try to give this a look Friday/ Saturday when I'm back home!

**Comment by JoernBerkefeld** [comment]
hi @david-robuck 

there was a breaking change in the format of importFiles in 7.0.0.
please either re-retrieve your importFile activity or update your template manually to:

```json
{
    "allowErrors": true,
    "customerKey": "SYS-LOL-camp-enrolment-staging-au",
    "createdDate": "2024-05-20T18:46:09.963",
    "modifiedDate": "2024-05-20T22:04:13.817",
    "dateFormatLocale": "en-US",
    "deleteFile": false,
    "fieldMappings": [],
    "fieldMappingType": "InferFromColumnHeadings",
    "fileNamingPattern": "camp_enrolment.csv",
    "fileType": "CSV",
    "filter": "",
    "hasColumnHeader": true,
    "isOrderedImport": true,
    "isSequential": true,
    "maxFileAgeHours": 0,
    "maxImportFrequencyHours": 0,
    "maxFileAgeScheduleOffsetHours": 0,
    "name": "Lola - Camp Enrolment Staging AU",
    "notificationEmailAddress": "",
    "sendEmailNotification": false,
    "standardQuotedStrings": true,
    "fileTransferLocationTypeId": 0,
    "destination": {
        "c__destinationType": "DataExtension",
        "r__dataExtension_key": "SYS-LOL-camp-enrolment-staging-au"
    },
    "source": {
        "r__fileLocation_name": "SFTP - Import"
    },
    "c__subscriberImportType": "DataExtension",
    "c__dataAction": "Overwrite"
}
```

**Comment by JoernBerkefeld** [comment]
i'll close the ticket, assuming that the above will help you get around your problem. I would appreciate a quick feedback though :)

**Comment by david-robuck** [comment]
Thank you @JoernBerkefeld that was very helpful. Good to know there is a new feature coming too :)

**Comment by JoernBerkefeld** [comment]
I added a full migration guide: https://github.com/Accenture/sfmc-devtools/wiki/03.-Updating-mcdev#migration-guide---v6-to-v7

**Comment by JoernBerkefeld** [comment]
Ok fixed: 


| v6 | v7 |
| :--- | :--- |
| c__destinationType | destination.c__destinationType |
| r__dataExtension_CustomerKey | destination.r__dataExtension_key |
| c__codeKeyword | destination.r__mobileKeyword_key |
| r__list_PathName | destination.r__list_PathName |
| c__sourceObjectKey | source.r__dataExtension_key |
| r__fileLocation_name | source.r__fileLocation_name |
