### ISSUE TITLE
[BUG] Data Extension folder creation bug (7.0.0)

### ISSUE THREAD

**Issue by ccarswell** [Accenture/sfmc-devtools#1377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error being shown when deploying Data Extensions using mcdev deploy. The issue is related to creating the folders for Data Extensions.  If the Data Extensions have been created, the error disappears.  When rolling back to previous version of sfmcdevtools (6.0.2) this issue is resolved.
![image](https://github.com/Accenture/sfmc-devtools/assets/28913874/322fc026-311e-4c26-896a-b7f12648970f)

### Expected Behavior

Folders should be created for Data Extensions when using mcdev deploy

### Steps To Reproduce

1. Deploy a Data Extension to a non-existent folder using mcdev deploy
2. Error is show as above

### Version

7.0.0

### Environment

- OS:
- Node:
- npm:

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by JoernBerkefeld** [comment]
i'll have a look ASAP. thank you for reporting this! :)

**Comment by JoernBerkefeld** [comment]
could you please try to reproduce the error but append "--api=log" to your command?
e.g. `mcdev deploy cred/bu dataExtension --api=log"
... and then upload your latest log file from the /logs/ folder? It will hopefully be either to debug it then

**Comment by JoernBerkefeld** [comment]
ok, was able to reproduce & fix that 
![image](https://github.com/Accenture/sfmc-devtools/assets/1917227/85a0d43d-dee7-4951-b3df-2095ea51f266)

**Comment by JoernBerkefeld** [comment]
fixed & released with 7.0.2
