### ISSUE TITLE
[BUG] Error retrieving when BU contains a dataextension without a CategoryID

### ISSUE THREAD

**Issue by fbellgr** [Accenture/sfmc-devtools#140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While running `mcdev retrieve` for the type dataextension, I ran into a problem during the retrieval of metadata.
As a result, none of the data extensions were retrieved.

```
13:08:00.135 debug: TypeError: Cannot read property 'Fields' of undefined
    at /usr/lib/node_modules/mcdev/lib/metadataTypes/DataExtension.js:316:59
    at Array.forEach (<anonymous>)
    at Function.retrieve (/usr/lib/node_modules/mcdev/lib/metadataTypes/DataExtension.js:314:23)
    at async /usr/lib/node_modules/mcdev/lib/Retriever.js:101:34
    at async Object.retryOnError (/usr/lib/node_modules/mcdev/lib/util/util.js:682:13)
    at async Retriever.retrieve (/usr/lib/node_modules/mcdev/lib/Retriever.js:100:21)
    at async _retrieveBU (/usr/lib/node_modules/mcdev/lib/index.js:683:13)
    at async retrieve (/usr/lib/node_modules/mcdev/lib/index.js:582:17)
```
By changing the code around `DataExtension.js:316:59` from

```
fieldKeys.forEach((key) => {
    const field = fieldsObj[key];
    metadata[field.DataExtension.CustomerKey].Fields.push(field);
});
```
to 
```
fieldKeys.forEach((key) => {
    const field = fieldsObj[key];
    if(metadata[field?.DataExtension?.CustomerKey]) {
        metadata[field.DataExtension.CustomerKey].Fields.push(field);
    }
    else {
        Util.logger.warn(`Issue retrieving fields. key='${key}'`);
    }
});
```
I could complete the retrieve process and find a corrupted data extension. It turns out that this data extension had no CategoryID at all.

There are a lot of problems of this nature in Markerting Cloud. The most frequents are folders whose parent does not exist. But I had never seen a data extension without a CategoryID before.

### Expected Behavior

I would expect that the process skips over the corrupted data extension and completes the retrieval.

I would also expect feedback containing the name and customer key of the corrupted data extension.

### Steps To Reproduce

Sadly, I cannot think of a way to reproduce this. It certainly originates from a bug in Marketing Cloud when deleting data extensions or folders, under certain circumstances.

It is reminiscent of the problem of orphan folders, of which I see plenty in most accounts and BUs.

### Version

3.0.3 (Default)

### Environment

- OS: Windows 10 (WSL 2 / Unbuntu Ubuntu 20.04.3 LTS)
- Node: 14.18.0
- npm: 6.14.15

**Comment by JoernBerkefeld** [comment]
@fbellgr thank you for finding this - would you want to open a PR for it given that you already found a solution? :-)
