### ISSUE TITLE
[FEATURE] How long will the journey deploy feature be - where is it in the backlog? Do you have a timescale?

### ISSUE THREAD

**Issue by kabads** [Accenture/sfmc-devtools#142]
**Is your feature request related to a problem? Please describe.**
We need to deploy journies, currently, we can only retrieve them at the moment. 

**Describe the solution you'd like**
After retrieve we can deploy if a journey is in the retrieve. 

**Describe alternatives you've considered**
Not using the sfmc tool :-(

**Comment by DougMidgley** [comment]
Hello @kabads
It is a common request we have and we have actively decided not the support this feature for now from our side, however if you would like to take an attempt, we can happily consider a contribution.
Generally there are two reasons for this
1) Package Manager was released this year and has a strong focus on Journeys & Marketing Users more broadly. We feel this tool is likely better suited to the users at the point.
2) There is extensive dependencies which we would need to be able to support to make this work, specifically being able to recreate the entire contact builder model via API, which is currently not supported. Without this,the majority of decision splits would likely not work so it is a large blocking factor.
