### ISSUE TITLE
[TASK] Missing asset type, asset retrieval by ID and wrong param order

### ISSUE THREAD

**Issue by fbellgr** [Accenture/sfmc-devtools#144]
A few issue with asset retrieval and deployment.

From the description of the pull request I made to address this:

https://github.com/Accenture/sfmc-devtools/pull/143

- Asset.definition is missing typeMapping entry for .ai
- Method Asset._readExtendedFileFromFS was being called with wrong parameters order
- Changed the filter in Asset to use type ids instead of type names, which solves the 10k limit at the source.

There appear to be measures taken to work around a limitation of 10k assets when using certain filter. It did not allow me to retrieve more than 10k. But I have an app that use this API in a similar manner, so I knew there was no 10k limit when using type ids.

**Closing note**

This is not part of this issue. I am simply pointing out code that might not be executed anymore.
Maybe you would like to rewrite this part of the code since the first 'if' should never be true anymore?

`lib\metadataTypes\Asset.js:231`

```
if (response.body.message && response.body.message.includes('all shards failed')) {
    // When running certain filters, there is a limit of 10k on ElastiCache.
    // Since we sort by ID, we can get the last ID then run new requests from there
    options.json.query = {
        leftOperand: {
            property: 'assetType.id',
            simpleOperator: 'in',
            value: subtypeIds,
        },
        logicalOperator: 'AND',
        rightOperand: {
            property: 'id',
            simpleOperator: 'greaterThan',
            value: items[items.length - 1].id,
        },
    };
    lastPage = 0;
    moreResults = true;
} else if (response.body.page * response.body.pageSize < response.body.count) {
    moreResults = true;
    lastPage = Number(response.body.page);
} else {
    moreResults = false;
}
```

**Comment by JoernBerkefeld** [comment]
this seems to be 2 topics in one: 1 bug & 1 enhancement. let's aim to split this up into multiple ones going forward ;-)

**Comment by JoernBerkefeld** [comment]
hi @fbellgr  - a friend of the project actually found a case in which we could push the number of retrieved assets from 10k to 23.050:

**before:**
![image](https://user-images.githubusercontent.com/1917227/146514077-c0b80a30-b797-42fa-af58-6cfd5fef624e.png)

**after:**
![image](https://user-images.githubusercontent.com/1917227/146514128-16e27dd2-9565-41ac-93c1-06a1de32f93e.png)

I was told the UI stated something around 32k though. Any thoughts? ;-)

**Comment by fbellgr** [comment]
Hi @JoernBerkefeld 

Are you asking me a question, or referring to me? ;) I can't tell.
You seem to be describing what my pull request does, which is eliminating the 10k limit.

I don't know of any limit in Content Builder. I don't use it very much. I think I have a little under 32k images in the account I am currently working on. I'd have to look at other accounts we have. I don't know when that will happen.

Regards

**Comment by JoernBerkefeld** [comment]
Actually I was asking ;-) 
But in the meantime I realized that the standard settings im mcdev exclude binary files while of course content builder shows the overall total. When we did the above test, we didn't change the default retrieve list to actually include those... 

I suppose I forgot how my own solution works 😅
