### ISSUE TITLE
[BUG] Retrieve taking 30 minutes for 1679 assets

### ISSUE THREAD

**Issue by ccarswell** [Accenture/sfmc-devtools#1440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

mcdev retrieve on a Business Unit took over 30 minutes for 1679 assets to be downloaded. I'm sure it didn't take this long in the previous version of MCDevTools (v6).
![image](https://github.com/Accenture/sfmc-devtools/assets/28913874/103c28bb-4c3a-487f-a62d-e5c8fed484f7)

### Expected Behavior

Previously I remember it taking only a minute or two. Might want to take a look into this, whether this is normal.

### Steps To Reproduce

3. Run '...'
4. See error...

### Version

7.0.4

### Environment

- OS:
- Node:
- npm:

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by JoernBerkefeld** [comment]
could it be that "previously" you didnt have 1600 emails in content builder on that BU?
Looking at your log, the other types were processed as per expectation but if you hit the API this much SFMC sometimes applies throttling for your IP... I'm assuming this might have happened on top

**Comment by JoernBerkefeld** [comment]
recent example from myself in which i downloaded 958 assets in under 2 minutes:
![image](https://github.com/user-attachments/assets/357b79d5-658b-4940-a9cc-69bc03344840)

pretty sure that you had internet / throttling issues
