### ISSUE TITLE
[FEATURE] remove "mcdev" from commands

### ISSUE THREAD

**Issue by Beryl-18** [Accenture/sfmc-devtools#1572]
Not much context here. I was just considering this as it seems repetitive. unless theres a purpose for it, and in the interest of doing lesser non repetitive tasks, why not ignore the word 'mcdev' altogether and just have retrieve bu/childbu dataExtension name, for example? feels a bit faster

**Comment by JoernBerkefeld** [comment]
Unfortunately, that will lead to more problems than it solves. SFMC DevTools are often used on computers with many other Tools installed and to avoid name space collisions, the common practice is to define a short, easily memorized "prefix" that runs it all. For Salesforce core's CLI that was "sfdx", now it's "sf". For this Tool, it's "mcdev".
