### ISSUE TITLE
[BUG] Prettier parser overrides not working

### ISSUE THREAD

**Issue by BlakeTnr** [Accenture/sfmc-devtools#1574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Parser overrides do not work in .prettierrc

### Expected Behavior

Overrides should apply rather than what sfmc decides at runtime

### Steps To Reproduce

Create a override and assign a parser in your .prettierc file, it won't work

### Version

7.1.4

### Environment

- OS: Windows
- Node: v20.11.0
- npm: 10.2.4

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by JoernBerkefeld** [comment]
will be released together with 7.1.5
