### ISSUE TITLE
[BUG] retrieveAsTemplate bug when using filename prefixes and suffixes

### ISSUE THREAD

**Issue by ccarswell** [Accenture/sfmc-devtools#168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running a "rt" command on a query that contains prefixes and suffixes in filename (example)  {{{prefix}}}[filename{{{suffix}}}) two files are created: a json file and a .sql file.  The json file is correctly generated with  {{{prefix}}}[filename{{{suffix}}}.json but the .sql file doesn't have the {{{prefix}}}[filename{{{suffix}}} and instead remains as before ([filename]).  This results in an error when running the "bd" command: "No such file or directory [filename].sql"

### Expected Behavior

We expect both the .json and the .sql file to contain the {{{prefix}}}[filename{{{suffix}}}.

### Steps To Reproduce

- Run "rt" on a query that is expecting to replace part of the filename itself as part of the "Markets" configuration
- Examine the files in template/query
- 1x .json file is created with the correct suffix/prefix {{{prefix}}}[filename{{{suffix}}}
- 1x. sql file is created without the correct suffix/prefix [filename]

Workaround is to rename the .sql filename to {{{prefix}}}[filename{{{suffix}}} before running the bd command

### Version

3.1.0 (Default)

### Environment

- OS: Windows 10
- Node: 14.17.4
- npm: 8.3.0

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by JoernBerkefeld** [comment]
confirming issue:;
![image](https://user-images.githubusercontent.com/1917227/149127253-de30acad-0078-446a-ac86-30a12b9299b5.png)

**Comment by JoernBerkefeld** [comment]
in reality, this is a bug on **retrieveAsTemplate** - the replacement shouldn't be happening on the filename for templates stored in the /template/ folder but only on its content (e.g. json)
