### ISSUE TITLE
Send correct exit code depending on error or success / CSCLSROZ-275

### ISSUE THREAD

**Issue by SabrinaEspino** [Accenture/sfmc-devtools#17]
code = 0 --> all ok

code = 1 --> error happened

how to: [https://stackoverflow.com/questions/5266152/how-to-exit-in-node-js](https://stackoverflow.com/questions/5266152/how-to-exit-in-node-js) 

 

devops solutions can listen for that end then show the build status correctly. right now, the build status is always green/OK because we handle all errors gracefully and by node apps default seem to send code 0

**Comment by JoernBerkefeld** [comment]
idea from @drcopado: only send these codes when extra parameter "--ci" was set to not annoy developers that use it but properly exit CICD pipeline code

**Comment by JoernBerkefeld** [comment]
started working on this by adding Util.logger.errorFatal() - we now need to switch from the default error() to errorFatal() for all those messages that should result in a CI/CD pipeline from noticing it
FYI @DougMidgley
