### ISSUE TITLE
include buildTemplate in createDeltaPkg instead of retrieveAsTemplate / CSCLSROZ-555

### ISSUE THREAD

**Issue by SabrinaEspino** [Accenture/sfmc-devtools#18]
the current approach does not actually use the files committed to git but retrieves again from the server -that might break things given that DEV might have already changed by the time this runs.

therefore, buildTemplate must be added which does what retrieveAsTemplate does, only completely local, without a retrieve

**Comment by JoernBerkefeld** [comment]
was duplicated by #19 - closed the other one to work in this one
