### ISSUE TITLE
[BUG] Executing `mcdev cdp` results in market configuration errors

### ISSUE THREAD

**Issue by dnivara-0** [Accenture/sfmc-devtools#1806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Current Behavior:**
Running `mcdev cdp` results in the following error message:
> `Could not find the market 'M' in your configuration file.`

I've been investigating this repository for about 3 hours and may not fully understand the code structure. I encountered this issue while setting up `mcdev` today, so please correct me if my interpretation is incorrect.

**Observed Issue:**
The issue appears to stem from the handling of `market` configuration data in the function `buildDeltaDefinitions` within `devops.js`.

In the code:
- **Line 423**: `const sourceMarket = Object.values(properties.marketList[sourceMlName])[0];`
  
  It appears that `sourceMarket` is assigned a string value.

- **Line 468**: `await Builder.buildTemplate(bu, type, keyArr, sourceMarket);`

  Here, the string `sourceMarket` is passed to the `buildTemplate` function.

Within `lib/Builder.js`, in the `buildTemplate` function, there’s a loop:
```javascript
for (const market of marketArr) {
    if (Util.checkMarket(market, properties)) {
        Object.assign(templateVariables, properties.markets[market]);
    } else {
        // do not execute the rest of this method if a market was invalid
        return;
    }
}
```
The code expects `marketArr` to be an array. However, since sourceMarket is a string, this discrepancy causes Util.checkMarket to return false for any market name(in my case it starts with 'M') leading to a failure in template generation.

**Impact:**
- Template files are not generated as expected, preventing subsequent `bdp` commands from executing successfully.

**Potential Cause:**
This behavior may have been introduced in [this PR](https://github.com/Accenture/sfmc-devtools/blob/978daefec828a56c5943cc5538e29fd73159b982/lib/Builder.js#L124), where handling for `marketArr` does not account for string inputs in cases like mine.

### Steps To Reproduce

3. Run '...'
4. See error...

### Version

7.4.4

### Environment

- OS: MacOS
- Node: 20.11.1
- npm: 10.8.3

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by JoernBerkefeld** [comment]
nicely detailed bug report! thank you. looking into the details and will try to reproduce this on my end
