### ISSUE TITLE
[BUG] mcdev bdb fails to find template where name and key differ

### ISSUE THREAD

**Issue by DougMidgley** [Accenture/sfmc-devtools#187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when trying to build a definition from a template, the process will look for a name, not a key.

### Expected Behavior

the logic should look for the key, as this is the value which stored by default as the filename

### Steps To Reproduce

22:19:56.607 debug: :: mcdev 3.1.0 ::
22:19:57.528 info: mcdev:: Build Definition from Template Bulk
22:19:57.530 info: Executing for 'training/MCDEV_Training_Target_1': 'QA'
22:19:57.531 info: mcdev:: Build Definition from Template
22:19:57.555 error: mcdev.buildDefinition:automation:: Could not find ./template\automation\Barcelona Automation.automation-meta.json.
22:19:57.555 debug: Error: automation:: Could not find ./template\automation\Barcelona Automation.automation-meta.json.
    at Function.buildDefinition (C:\Users\douglas.midgley\AppData\Roaming\npm\node_modules\mcdev\lib\metadataTypes\MetadataType.js:1273:23)
    at async Promise.all (index 0)
    at async Builder.buildDefinition (C:\Users\douglas.midgley\AppData\Roaming\npm\node_modules\mcdev\lib\Builder.js:69:28)

### Version

3.1.2

### Environment

- OS:
- Node:
- npm:

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by JoernBerkefeld** [comment]
making matters worse, in the current 3.1.3 on #develop we get to see another bug when running `rt automation`:

![image](https://user-images.githubusercontent.com/1917227/154969884-2d94355f-4904-4d8f-a02b-164a2a4d289b.png)
