### ISSUE TITLE
add `buildTemplate` based on `rt` command that uses retrieve folder and not server as source / CSCLSROZ-230

### ISSUE THREAD

**Issue by SabrinaEspino** [Accenture/sfmc-devtools#19]
the current approach does not actually use the files committed to git but retrieves again from the server -that might break things given that DEV might have already changed by the time this runs.

therefore, **buildTemplate** must be added which does what retrieveAsTemplate does, only completely local, without a retrieve

**Comment by JoernBerkefeld** [comment]
duplicates #18
