### ISSUE TITLE
[BUG] mcdev refresh -m triggeredSend fails with no keys provided error

### ISSUE THREAD

**Issue by PriyajitGhosh1995** [Accenture/sfmc-devtools#1942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/user-attachments/assets/f97ba4ba-964c-4106-82bc-cca2a423b7c4)

### Expected Behavior

Refresh should have worked

### Version

7.6.0

### Environment

- OS:
- Node:
- npm:

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by JoernBerkefeld** [comment]
damn it :D
