### ISSUE TITLE
[BUG] FTP Location Not Recognized and Throwing an Error

### ISSUE THREAD

**Issue by solariimeow** [Accenture/sfmc-devtools#199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

FTP location isn't recognized and the tool keeps throwing an error when the FTP location has been created already.
<img width="694" alt="FTP Location Error" src="https://user-images.githubusercontent.com/45225495/155162548-e7103ce3-fb95-4467-bd0c-5bb4aebdd783.PNG">
Trying to deploy automation into a new instance. Already created a new FTP loc with the same name and same setup in the target instance.
<img width="531" alt="FTP Location" src="https://user-images.githubusercontent.com/45225495/155162795-b932277d-5f71-44ba-a568-5a3eb467619b.PNG">

### Expected Behavior

Be able to deploy automation without issue.

### Steps To Reproduce

1. Extract the automation from the source BU with retrieve command.
2. Deploy the automation along with its dependencies.
3. Throws an error "Missing one or more dependent metadata. ftpLocation with name='Data Extract Exports' was not found on your BU"
4. Grabbed the FTP location and dropped it in the deploy folder.
5. Created a new FTP loc in the new instance with the same structure as the source BU.
6. Throws an error "ftpLocation create: create not supported". See attached image above.

### Version

3.1.3

### Environment

- OS: Windows
- Node: 16.13.0
- npm: 8.4.0

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by JoernBerkefeld** [comment]
hi @solariimeow could you please try and retrieve `ftpLocation` to check if all 3 get downloaded? And if yes, post the JSON of the one that's causing this here?

1. run `mcdev retrieve . ftpLocation`
2. select credential
3. select BU
4. check results

the dot is just a placeholder that will kick mcdev into wizard mode - any other character would do the same

**Comment by JoernBerkefeld** [comment]
i just re-read your description and noticed you were already able to download it and that your bug is about deploying only, not retrieving.

sooo, **yes**, mcdev does not support deploying FTP Locations - that is mentioned in the overview table in the docs. But since that's usually a step not often done I suggest you put that into the pre-deployment steps to easily solve it.

why is it not supported? I could be wrong but I think the API endpoint was not made available by SFMC. Luckily, as pointed out above, it shouldn't be a big blocker.

**Comment by solariimeow** [comment]
Hi @JoernBerkefeld , thanks for the prompt response. I'm afraid the pre-deployment steps have been done but the error persists. For the time being, we've used Package Manager and worked. Perhaps you can look into this, I'd be happy to do the needful.

**Comment by JoernBerkefeld** [comment]
to make sure i understand correctly: you did create the FTP location manually and it still didn't work?

if yes could you attach the automation you are trying to attach?

and also the downloaded ftp location from your source BU , as well as the one on your target BU (I am suspecting some subtle difference...)

**Comment by solariimeow** [comment]
@JoernBerkefeld This is resolved. The FTP location was only created in the parent BU and not in our test BU. Thank you!

**Comment by JoernBerkefeld** [comment]
thank you for figuring this out and sharing the details! hope you'll enjoy the upcoming 3.2 upgrade ;-)
