### ISSUE TITLE
[BUG] mcdev createDeltaPkg

### ISSUE THREAD

**Issue by DougMidgley** [Accenture/sfmc-devtools#206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when committing delta for query activity, createDeltaPkg will attempt to try to use both sql and json files (resulting in two items being processed).

### Expected Behavior

createDeltaPkg should only process the json file.

### Steps To Reproduce

23:08:05.082 info: Retrieving as Template: query
23:08:05.709 info: Downloaded: query (0)
23:08:05.710 error: query 'Example_QA_DE' not found on server.
23:08:05.804 info: Downloaded: query (0)
23:08:05.805 error: query 'Example_QA_DE' not found on server.
23:08:05.806 info: - ✔️  Templates created
23:08:05.807 info: =============
23:08:05.808 info: Build definitions from delta templates
23:08:07.992 info: ⚡ mcdev bdb deployment-target query ","
23:08:07.993 info: mcdev:: Build Definition from Template Bulk
23:08:07.994 info: Executing for 'training/MCDEVDemo_France': 'FR'
23:08:07.995 info: mcdev:: Build Definition from Template
23:08:07.999 info: - ✔️  Deploy defintions created
23:08:08.021 info: You can now run deploy on the prepared BUs
23:08:08.024 error: mcdev.buildDefinition:query:: Could not find ./template\query\.query-meta.json.
23:08:08.025 debug: Error: query:: Could not find ./template\query\.query-meta.json.
    at Function.buildDefinition (C:\Users\douglas.midgley\workspace\sfmc-devtools\lib\metadataTypes\MetadataType.js:1140:23)
    at async Promise.all (index 0)
    at async Builder.buildDefinition (C:\Users\douglas.midgley\workspace\sfmc-devtools\lib\Builder.js:69:28)

### Version

3.1.3

### Environment

- OS: Windows
- Node: 17
- npm: 8.3

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by JoernBerkefeld** [comment]
assuming this will also be the same issue for other types that get saved in multiple files.
the impact should be low at this point because it just means stuff gets executed twice, but it shouldn't lead to things failing

**Comment by JoernBerkefeld** [comment]
note to self: the log from above shows errors but only due to the used edge case during testing where the git branches didn't reflect whats on the server. this edge case would be gone if #18  & #19 were done

**Comment by JoernBerkefeld** [comment]
this was caused by pointing to the wrong js file when running mcdev from copado.
index.js > for require/import
cli.js > for executing it on the command line
