### ISSUE TITLE
[BUG] Logs folder automatically created

### ISSUE THREAD

**Issue by Francois-BellegardeOSF** [Accenture/sfmc-devtools#207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever we run `mcdev`, even without parameters, a 'logs' folder is created.

### Expected Behavior

A logs folder should only be created if something actually happens or is actually written.

I would also think that this log folders makes sense only in an initialized project.

### Steps To Reproduce

1. install the current version: `npm i -g mcdev`
2. navigate to an empty folder
3. Run `mcdev`
4. Notice the new 'logs' folder that was created

Even running `mcdev --version` creates a 'logs' folder.

### Version

3.1.3

### Environment

- OS: Windows/WSL/Linux
- Node: 14.17.0, 14.18.2, 16.13.2
- npm: 7.24.2, 8.3.0, 8.5.1

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by francois-bellegardeOSF** [comment]
It pollutes whatever location you call it from, even when you don't want to accomplish anything.

If you run even just `mcdev --help` from a location that is readonly, it shows an ugly unhandled error. I think at the very least it is a nuisance.

![image](https://user-images.githubusercontent.com/99818098/159741095-aa455c07-6e37-4602-b8e3-49af15daeb2b.png)

I'm simply reporting what I find.

**Comment by JoernBerkefeld** [comment]
i wonder - what folder were you in when the above error happened? and what system & cli are u using?
It looks to me like you were in some admin-only folder when you ran that and mcdev wasn't executed with admin rights at the time?

Asking because I **can** reproduce the folder creation but I **cannot** reproduce the error

**Comment by JoernBerkefeld** [comment]
fixing the folder creation will need a rewrite of how we start logging. I don't think we'll tackle that before the next release but potentially in a patch soon after

the read-only dir issue is a problem that needs sorting inside of winston, which is the external module we use for logging

**Comment by JoernBerkefeld** [comment]
finally tackling this ticket to then fix #969 afterwards ;-)

**Comment by JoernBerkefeld** [comment]
@Francois-BellegardeOSF quick note on how I tackled this: the access issue wasn't touched buy I simply made sure that commands that don't require a log file simply don't get one anymore, regardless of the folder you are in.
Every command that ends up writing into the current folder, however, does get a log file.

To avoid log files all together for, I suppose, other reasons, you can use --noLogFile from 5.1 on.
