### ISSUE TITLE
[BUG] Roles Cannot be updated due to missing ObjectID in payload

### ISSUE THREAD

**Issue by DougMidgley** [Accenture/sfmc-devtools#210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating roles, no issues, but updating there is a ObjectID missing in the payload, which stops it from updating the record. Unfortunately, it seems CustomerKey cannot be used with Role as an upsert value.

### Expected Behavior

Update of roles should perform as create roles.

### Steps To Reproduce

Download Roles from any org
Move to deploy folder, and deploy

### Version

3.1.3

### Environment

- OS: Windows
- Node: 17
- npm: 8

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by JoernBerkefeld** [comment]
still failing after the one commit, though with a different error:

**before:**
![image](https://user-images.githubusercontent.com/1917227/160096097-87d53fba-3788-470f-a5b6-f27118fa5f08.png)

**now:**
![image](https://user-images.githubusercontent.com/1917227/160095916-ce142050-2a3d-4e11-a048-9c1935947f6e.png)

**Comment by JoernBerkefeld** [comment]
stack trace 
10:40:57.791 debug: TypeError: Cannot read property 'Results' of undefined
    at C:\Git\sfmc-devtools\lib\metadataTypes\MetadataType.js:343:36
    at Array.map (<anonymous>)
    at Function.upsert (C:\Git\sfmc-devtools\lib\metadataTypes\MetadataType.js:343:18)
    at async Function.deploy (C:\Git\sfmc-devtools\lib\metadataTypes\MetadataType.js:121:31)
    at async Deployer.deploy (C:\Git\sfmc-devtools\lib\Deployer.js:92:32)
    at async Function._deployBU (C:\Git\sfmc-devtools\lib\index.js:487:17)
    at async Function.deploy (C:\Git\sfmc-devtools\lib\index.js:578:17)
