### ISSUE TITLE
[BUG] Can't retrieve as template any dataExtract file 

### ISSUE THREAD

**Issue by Micfli** [Accenture/sfmc-devtools#267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can't retrieve as template any dataExtract file, When I try to use 'mvdev rt' cmd I am getting an error showed in the image bellow:

<img width="565" alt="image" src="https://user-images.githubusercontent.com/90446461/163180060-65caef4c-148f-431b-bea4-13be679c48c5.png">

### Expected Behavior

I expected to retrieve dataExtract file as a template.

### Steps To Reproduce

3. Run '...'
4. See error...

### Version

3.2.0

### Environment

- OS: Windows 10
- Node: 17.7.1
- npm: 8.5.2

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by DougMidgley** [comment]
I did some testing and found a bug, not sure it is identical to this one, but either way it is now working for me in the next version (v4)
