### ISSUE TITLE
catalyst upgrade must check if .catalyst-auth.json is present / CSCLSROZ-427

### ISSUE THREAD

**Issue by SabrinaEspino** [Accenture/sfmc-devtools#28]
if you run catalyst upgrade on a project-folder after cloning the repo it will fail on upgrading .catalystrc (the config file) but continue doing other things.

 

either silently ignore this part or error out completely.

 

--> could be a general error if the auth file is missing. should fail and ask to run catalyst init

**Comment by JoernBerkefeld** [comment]
too old now. closing
