### ISSUE TITLE
rewrite inquirer logic to purge unneeded promise wrappers / CSCLSROZ-126

### ISSUE THREAD

**Issue by SabrinaEspino** [Accenture/sfmc-devtools#30]
from docs -> var inquirer = require('inquirer');
inquirer
.prompt([
/* Pass your questions in here */
])
.then(answers => {
// Use user feedback for... whatever!!
})
.catch(error => {
if(error.isTtyError) {
// Prompt couldn't be rendered in the current environment
} else {
// Something else when wrong
}
});

so the following does the same thing.
const responses = await inquirer.prompt(questions);

**Comment by JoernBerkefeld** [comment]
@DougMidgley  - i feel like you've done that already, havent you? if yes, we can remove the milestone close it

**Comment by JoernBerkefeld** [comment]
Rewrote as Part of 7.1
