### ISSUE TITLE
[FEATURE] Add support for Data Verfication activity in Automation.

### ISSUE THREAD

**Issue by bgacek** [Accenture/sfmc-devtools#325]
**Is your feature request related to a problem? Please describe.**

Unable to deploy the Data Verification Activity as part of my Automation.

**Describe the solution you'd like**

Be able to deploy the Data Verification Activity as part of my Automation deployment routine.

**Describe alternatives you've considered**

Manually creating and updating the activity through Automation Studio UI, or writing myself REST API requests. 

**Additional context**

Tested myself and found out that there is an REST endpoint which allows to READ/CREATE/MODIFY the Data Verification Activities. More details below.

Endpoint: `/automation/v1/dataverifications/{id}`
Supported Methods:  `GET/POST/PATCH`

**Examples:** 

**GET**: `/automation/v1/dataverifications/{dataVerificationDefinitionId}`
Response:

```
{
    dataVerificationDefinitionId: 'dataVerificationDefinitionId',
    targetObjectId: 'dataExtensionObjectId',
    verificationType: 'IsEqualTo',
    value1: 0,
    value2: 0,
    shouldStopOnFailure: true,
    shouldEmailOnFailure: false,
    notificationEmailAddress: '',
    notificationEmailMessage: '',
    createdBy: userId
}
```

**POST**: `/automation/v1/dataverifications/`
Request: 

```
{
  "destinationName": "Name",
  "deDestinationName": "DE Name",
  "targetObjectId": "DE Object ID",
  "deTotalRowCount": 0,
  "deFieldCount": 5,
  "deModifiedDate": "2022-04-06T15:54:14Z",
  "deModifiedByName": "Some User",
  "value1": 0,
  "conditionText1": "is",
  "conditionText2": "equal to",
  "notificationEmailAddress": "",
  "verificationType": "IsEqualTo",
  "shouldStopOnFailure": 1,
  "notificationEmailMessage": "",
  "shouldEmailOnFailure": 0
}
```

Response: Same as in GET Request

**PATCH**: `/automation/v1/dataverifications/{dataVerificationDefinitionId}`
Request: 

```
{
  "dataVerificationDefinitionId": "dataVerificationDefinitionId",
  "targetObjectId": "dataExtensionObjectId",
  "verificationType": "IsEqualTo",
  "value1": 0,
  "value2": 0,
  "shouldStopOnFailure": true,
  "shouldEmailOnFailure": false,
  "notificationEmailAddress": "",
  "notificationEmailMessage": "",
  "createdBy": userId
}
```

Response: Same as in GET and POST

**Comment by DougMidgley** [comment]
@JoernBerkefeld  - no generic GET collection exists for this, so would need building into automation directly, not as a separete type. We could just nest to json to avoid issues, but would need to be clever about caching etc. thoughts?

**Comment by JoernBerkefeld** [comment]
copying info in from other ticket:
https://help.salesforce.com/articleView?id=mc_as_automation_studio_activities_reference.htm&type=5

**Comment by JoernBerkefeld** [comment]
looks like a bigger task for 4.1?
I do find it interesting and I sure like the groundwork done by @bgacek
