### ISSUE TITLE
Add Delete support for all metadata types / CSCLSROZ-356

### ISSUE THREAD

**Issue by SabrinaEspino** [Accenture/sfmc-devtools#34]
Subtasks:

## SOAP
- [x] Delete DataExtension
- [x] Delete DataExtensionField 
- [x] Delete EmailSendDefinition
- [x] Delete List
- [x] Delete TriggeredSend

## REST
- [ ] Delete Asset 
- [ ] Delete DataExtract 
- [ ] Delete FileTransfer
- [ ] Delete ImportFile
- [ ] Delete Query
- [ ] Delete Script

**Comment by JoernBerkefeld** [comment]
turned dataExtension delete logic into a generic method

**Comment by JoernBerkefeld** [comment]
decided to split rest off into separate issue #164
