### ISSUE TITLE
[BUG] dataExtensionField and dataExtension and folder is cached twice during `deploy dataExtension`

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/1917227/176407287-9caad3d5-485c-444d-9e65-7fc3c5332a87.png)

### Expected Behavior

cached only once

### Steps To Reproduce

3. Run '...'
4. See error...

### Version

develop-branch

### Environment

- OS:
- Node:
- npm:

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by DougMidgley** [comment]
https://github.com/Accenture/sfmc-devtools/blob/1dc2677a9d3f150fffdc475e0f0df6f03d144df8/lib/metadataTypes/DataExtension.js#L30 is largely the cause. 
Issue is that if we include isDeploy in the deployer.js class then an additional API call will be made for fields even when deploying metadata which is NOT data extension. Would require a bit more of a workaround

**Comment by JoernBerkefeld** [comment]
also, i believe you didnt _push_ yet
