### ISSUE TITLE
[Task] add in docs example for .mcdev-auth.json

### ISSUE THREAD

**Issue by dawidmachon** [Accenture/sfmc-devtools#378]
**Describe the solution you'd like**
I know there is` mcdev init`, but I think it's nice to add in docs example how it's structured

**Comment by DougMidgley** [comment]
we recently just changed how this work, normally, we would prefer to keep this added via CLI, which keeps consistency. You can always copy from there. @JoernBerkefeld  thoughts from your side?

**Comment by JoernBerkefeld** [comment]
done at https://github.com/Accenture/sfmc-devtools/wiki/7.-Advanced-Configuration#mcdev-authjson
