### ISSUE TITLE
[BUG] dataExtension docs not created

### ISSUE THREAD

**Issue by ccarswell** [Accenture/sfmc-devtools#387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After 'mcdev retrieve', the docs folder is empty except for "roles"

### Expected Behavior

Previously dataExtension was populated in md format

### Steps To Reproduce

1. mcdev retrieve
2. Go to folder 'docs'
3. No dataExtension folder

### Version

4.0.0

### Environment

- OS: Windows
- Node: 16.16.0
- npm: 8.3.0

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by JoernBerkefeld** [comment]
We moved them directly intro the retrieve folder, side by side with the json
