### ISSUE TITLE
git commit shows "unsupported format" warnings

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools#7]
happens when running mcdev init

unfortunatley this not only happens for our config files but also for ALL files initially downloaded from BUs... means one gets a LONG list of stupid errors

with git version 2.28.0 on windows:
![image](https://user-images.githubusercontent.com/1917227/114245287-7871db00-9990-11eb-8b1d-e056841c14b6.png)

![image](https://user-images.githubusercontent.com/1917227/114245313-87588d80-9990-11eb-9124-224d0975c6c0.png)

**Comment by DougMidgley** [comment]
https://stackoverflow.com/questions/66416032/warn-in-git-commit
seems to suggest that it might be the accenture hooks in the repo (.git/hooks/precommit)
have we tried this on a non-accenture pr?

**Comment by JoernBerkefeld** [comment]
nope - so far i had no clue why this was coming

**Comment by JoernBerkefeld** [comment]
could maybe be solved by 
![image](https://user-images.githubusercontent.com/1917227/168639429-2648ca6e-8b6d-4a4a-82a1-8c3cfb9f6248.png)

needs to be tested though for which I don't have time right now :D
