### ISSUE TITLE
[BUG] code snippets made up of ssjs are not saved as SSJS

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools#747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/1917227/219434390-25fbe634-2ac3-40e8-9993-19835771c31d.png)
only html or amp
but not ssjs is possible here

### Steps To Reproduce

3. Run '...'
4. See error...

### Version

4.3.3

### Environment

- OS:
- Node:
- npm:

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by david-robuck** [comment]
This update is going to be incredibly helpful in getting our team to fully embrace using mcdev as their primary tool. Thank you!
