### ISSUE TITLE
[BUG] cdp command creates templates only for a few assets in the templates folder

### ISSUE THREAD

**Issue by phjulia** [Accenture/sfmc-devtools#756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![template_folder](https://user-images.githubusercontent.com/79999614/220047342-a0155f87-d15a-43f6-b176-ce24562039b6.png)
cdp command created templates for one block and for 3 messages, while in the deploy folder 3 block assets were created and several messages (html files only/ see issue [755 ](https://github.com/Accenture/sfmc-devtools/issues/755)). Deploy folder was emptied before cdp command was run. The issue was reproduced with Estonia BU. 
Deploy folder: 
![deploy_folder](https://user-images.githubusercontent.com/79999614/220047356-87a6df60-98d9-4329-ac2b-44b6fe34ca5b.png)

### Steps To Reproduce

3. Run '...'
4. See error...

### Version

develop-branch

### Environment

- OS:
- Node:
- npm:

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by JoernBerkefeld** [comment]
this is not a bug but actually bad documentation:

if the --filter option is used then no markets / market lists are used - and it doesn't used buildTemplate nor buildDefinition.
instead it creates a 1:1 copy of relevant files in the deploy folder. this is particularly useful for people that make a lot of changes with search & replace and then don't know which files have to be deployed.

- [ ] update docs
