### ISSUE TITLE
[BUG] Query targetKey not updated with DE change

### ISSUE THREAD

**Issue by dawidmachon** [Accenture/sfmc-devtools#801]
Hi,
I am bringing small, pretty issue for you. But not sure if its applicable, because using slightly outdated version: 4.2.1.

Steps:

- Create Data Extension with custom external key.
- Create Query Activity using as target DE our new DataExtension.
- Retrieve by mcDevtools, configuration for query is okay. Holds correct key for DE.
- Change in MC our key for Data Extension
- Again fresh retrieve. Configuration holds old key still, but activity in MC itself working correctly.

Proof:
DE with custom key on creation:
![image](https://user-images.githubusercontent.com/44931854/224774395-89f6b6f8-81e9-41bc-8a6f-f1aa105e0e77.png)

configuration retrieved:
```json
{
    "name": "testquerymcdev",
    "key": "testquerymcdev",
    "description": "",
    "targetKey": "key1on1creation",
    "createdDate": "2023-03-13T10:44:01.89",
    "modifiedDate": "2023-03-13T10:44:01.89",
    "targetUpdateTypeName": "Overwrite",
    "isFrozen": false,
    "r__folder_Path": "Query"
}
```

DE with updated key:
![image](https://user-images.githubusercontent.com/44931854/224774791-45d56b72-abcf-43b7-a070-b9f7c1354dd3.png)

configuration retrieved:
```json
{
    "name": "testquerymcdev",
    "key": "testquerymcdev",
    "description": "",
    "targetKey": "key1on1creation",
    "createdDate": "2023-03-13T10:44:01.89",
    "modifiedDate": "2023-03-13T10:44:01.89",
    "targetUpdateTypeName": "Overwrite",
    "isFrozen": false,
    "r__folder_Path": "Query"
}
```

**Comment by barneygf** [comment]
I'm using 4.3.1 and I believe the same happens to me.

**Comment by barneygf** [comment]
I believe this is not the devtools bug, but the behaviour of SFMC. I just changed the External Key of the Automation via UI and try to retrieve its schedule via API, using Postman. I used new CustomerKey to do it, and got an info, that I need to used ObjectID instead. From my knowledge, that's not true, CustomerKey should be enough. So I tried also using Postman, to schedule Automation with the old CustomerKey and it worked.

**Comment by JoernBerkefeld** [comment]
hi @dawidmachon - i found something!
queries actually have a field that we don't save to the json, `targetId`. That field is the `ObjectID` of the target dataExtension and would always stay the same, even if you change the name or key. It seems, MC uses that one internally to look up the correct dataExtension... Why they would also save the name, key and description of the dataExtension on the query only the SFMC-gods will ever understand...

anyhow, I'm pushing an update that will rectify the query's JSON upon the next retrieve going forward :)

Thank you for making us aware of this issue, @dawidmachon
