### ISSUE TITLE
[BUG] Internal Server Error creating/updating dataExtract

### ISSUE THREAD

**Issue by andbolivar** [Accenture/sfmc-devtools#816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When im trying to deploy a dataExtract / automation i get this error msg:
![image](https://user-images.githubusercontent.com/13694714/227318148-0f216d6e-4c6e-4254-a2e4-e8d59f7f80c2.png)

The ID showing does not exist on my deploy folder and only happens when i try to deploy that 2 MetadataType. (Just to clarify deploys correctly on dataExtension and query MetadataType).
![image](https://user-images.githubusercontent.com/13694714/227320136-2576281c-5fe2-408d-a290-37edfd735c60.png)

### Expected Behavior

Be able to deploy automation without issue.

### Steps To Reproduce

1. Set the files on the deploy folder with the folder requirement name
2. Deploy the whole or the selected MetadataType

### Version

4.3.4

### Environment

- OS: Windows 11
- Node: v18.15.0
- npm:9.5.0

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by JoernBerkefeld** [comment]
hi @andbolivar - the id at the end of that endpoint is the SFMC-internal "ObjectID", not the key that we use in filenames. It's not visible in the GUI and cannot be changed. Some APIs require that.
could you please try this with just a single dataExtract in your deploy folder and - if that still fails, provide the log latest 2 log files (in your project's /log/ folder) as well as the dataExtract JSON you tried to deploy?

make sure you scrub the files from potentially visible client names. #cdp

**Comment by andbolivar** [comment]
Thanks for the assist, Jörn!
Still with the same issue
[541638D7-ABDA-434F-9769-F66404D409BE.txt](https://github.com/Accenture/sfmc-devtools/files/11062753/541638D7-ABDA-434F-9769-F66404D409BE.txt)
[2023-03-24T13.36.13.690Z-errors.log](https://github.com/Accenture/sfmc-devtools/files/11062767/2023-03-24T13.36.13.690Z-errors.log)
[2023-03-24T13.36.13.690Z.log](https://github.com/Accenture/sfmc-devtools/files/11062768/2023-03-24T13.36.13.690Z.log)

**Comment by JoernBerkefeld** [comment]
hm, nothing wrong with these. i couldnt deploy it with your extract type, because I didn't have that, but when I changed that to the default "Data Extension Extract" it worked like a charm. 
the type does seem to exist on your server given that there is no error about it in the log. could you try deploying it with a different extract type to test if it generally works?

**Comment by andbolivar** [comment]
Still got the same problem swaping to "r__dataExtractType_name": "Data Extension Extract".
I just remember i had to create a ticket to allow Salesforce to add Data Extension with the gzip. maybe they changed some value?.
There is a way to check the Rest call is sending the system?.
(Looks like Salesforce support might check on my BU)

**Comment by JoernBerkefeld** [comment]
i could do that on my system but instead I decided to add a new feature for it to enable you and others to get that: PR #820 will add it and it will land in release 4.4.0 soon.
please give me a few more days to get that released

**Comment by andbolivar** [comment]
Thanks. There is any way to assist to help you on the original problem, or only should i wait to the next release.

**Comment by JoernBerkefeld** [comment]
Thank you - but I do believe there is nothing more I could do at this point - I think you guessed into the right direction: salesforce might have messed something up when they provisioned that new extract type. Seen similar things before (e.g. missing standard folders om a new BU).

IF YOU DONT WANT TO WAIT:
In mcdev there is a folder lib/util and in there file auth.js: in that one you will find 2 commented lines of code. If you uncomment those and retry your deployment it should print the api calls to CLI...
If you then append " > my.log" to your command (mcdev deploy cred/bu dataExtract > my.log) all cli output will be saved to the specified file.

**Comment by JoernBerkefeld** [comment]
@andbolivar - did you ever have a chance to follow up on this with the new `--cli=log` parameter?

**Comment by andbolivar** [comment]
I gave it a try, on one BU with some configurations I could upload some
data. but on others without that i couldn't so far i need to pinpoint the
possible causes for that. so far looks like its Salesforce custom builds

**Comment by JoernBerkefeld** [comment]
did you ever get to solve this mystery, @andbolivar ?

**Comment by JoernBerkefeld** [comment]
closing this one for now. please feel free to re-open it if & when you are ready to continue it.
#ghostInTheMachine
