### ISSUE TITLE
[BUG] Retrieving data in the backup job ends with an error and code '1' instead of a warning

### ISSUE THREAD

**Issue by asia962** [Accenture/sfmc-devtools#827]
During the backup job and retrieving data from one of the Business Unit with invalid credentials, the error occurred that resulted in exiting with code '1'.  In case the credentials are invalid we would like to see only a warning, not an error, that stops the job. 
I attach a screenshot of this error.

![error](https://user-images.githubusercontent.com/78918300/228545400-19cded23-2c16-4a52-8c6c-701b246841d8.jpg)
![Zrzut ekranu 2023-03-29 144840](https://user-images.githubusercontent.com/78918300/228546653-578f2a17-b8d4-4bda-b06c-7bcc48ccd7f7.png)

**Comment by JoernBerkefeld** [comment]
Hi @asia962 - might i suggest removing that particular BU from your `.mcdevrc.json` instead?
You would need to find that particular BU in this list:
![image](https://user-images.githubusercontent.com/1917227/228557178-561fcf44-c27b-4b8d-bdc6-5cda0d1297e7.png)
... and remove the line in question.

This way, mcdev retrieve * will no longer know about that BU, and you won't run into this issue.

Any event that we qualified as an "error" will automatically set the exitCode to 1. That's been implemented specifically for unattended use cases of mcdev, like the backup you are running and CI/CD setups. Something did not work as expected and is not recoverable - like missing access to a BU. And given that there is the above solution to your problem, I don't expect that we will change that particular behavior.
