### ISSUE TITLE
[TASK] Decide whether missing dependencies during download should cause warn or error & skip or download / CSCLSROZ-546

### ISSUE THREAD

**Issue by SarikaBhosale11** [Accenture/sfmc-devtools#85]
**ERROR:**

- importFile:

![image](https://user-images.githubusercontent.com/77027445/127850270-361bc5bc-044f-4773-80a4-b63fee2ee312.png)

- automation

![image](https://user-images.githubusercontent.com/77027445/127850301-7fa20211-d2d0-4cd6-a701-75d803a56a5d.png)

 

**WARN:**

- emailSendDefinition:

![image](https://user-images.githubusercontent.com/77027445/127850415-424f2d88-7f8e-40a6-8a60-29bc05d6dcc3.png)

- dataExtension:

![image](https://user-images.githubusercontent.com/77027445/127850436-53d4b503-e39e-4dff-864b-239e8434b1d9.png)

- triggeredSendDefinition:

![image](https://user-images.githubusercontent.com/77027445/127850467-89a987e9-07ff-421a-8186-d4d3e3ca75c2.png)

- query

![image](https://user-images.githubusercontent.com/77027445/127850498-162376e8-c96c-4c7e-b828-01134461ca4c.png)

**Comment by JoernBerkefeld** [comment]
this was decided and hence closed by #17 which required this decision to be made. missing dependencies are a warning during retrieve and an error during deploy
