### ISSUE TITLE
Question regarding template assets

### ISSUE THREAD

**Issue by richard-tate-cf** [Accenture/sfmc-devtools#943]
Just wanted to know if there any know issues with using this tool with html email templates, when trying to update an existing template?

**Comment by JoernBerkefeld** [comment]
just one at the moment: 
- #798


You can check the list itself though - we don't keep hidden secondary list anywhere: https://github.com/Accenture/sfmc-devtools/issues?q=is%3Aissue+is%3Aopen+asset+label%3Abug
