### ISSUE TITLE
[TASK] rewrite util/** to static classes to improve IntelliSense (outline) / CSCLSROZ-404

### ISSUE THREAD

**Issue by SarikaBhosale11** [Accenture/sfmc-devtools#98]
turn this
![image](https://user-images.githubusercontent.com/1917227/177123054-59cd32ff-9029-4e33-b926-5c14018abd88.png)

into
![image](https://user-images.githubusercontent.com/1917227/177122925-802ec84e-0989-4bfb-9535-0a4b50d81e85.png)

**for every file in lib/util**

**Comment by tuliodnw** [comment]
@JoernBerkefeld when writting it to static classes, what should i do with the defined var?

move them to a constructor as in here?
![image](https://user-images.githubusercontent.com/18468905/180766064-c06c7b2f-656e-4c47-af1c-d0c911b51bb3.png)

or is there a better aproach?

**Comment by JoernBerkefeld** [comment]
If it was part of the object, just define it as a static property with whatever initial value we had before. Constructors are for non-static classes only, as in classes that have methods that are not marked as static. 
Here we want all methods to be declared static and hence avoid creating an instance of the class when using it (which is where the constructor could be used)

**Comment by tuliodnw** [comment]
![image](https://user-images.githubusercontent.com/18468905/180781871-16df8140-83ed-4060-a27f-98d204237591.png)
i have it like this and i get no errors or warnings. but i am missing something out. 


when i call Util.boilerplateDirectory, from any other location i get the result undefined, even tho when i click Util.boilerplateDirectory everything is connected correctly.

**Comment by tuliodnw** [comment]
![image](https://user-images.githubusercontent.com/18468905/180819848-b46b5079-f0c3-444b-bdba-052bca6c3ce2.png)
![2022-07-25_17h45_52](https://user-images.githubusercontent.com/18468905/180819993-e66b1e4e-feb0-4848-a9e3-4e933fb47b5d.png)

in a test bench it works, but in sfmc the value comes as undefined. 
writing the static property also gives me eslint errors.

any ideas?

**Comment by JoernBerkefeld** [comment]
Check out the the error&warning log in vscode. It will have at least one item for you to fix. Alternatively, check your Screenshot for Red underlines and hover that in vscode (hint: line 2)

**Comment by tuliodnw** [comment]
the problem arises from File.js after the class is static exporting both modules doesnt work with File only fs functions are being passed
```
cons FileFs = { ...File, ...fs }; // also tried consFileFs = { File, ...fs };
FileFs.prettierConfig = null;
module.exports = FileFs;
```

i can pass the module for File like this. and import fs separately.
```
module.exports = File;
```

and rewrite `File.pathExists(Util.configFileName) to fs.pathExists(Util.configFileName)`

should i do it like this?, Ana recommended me this solution
